FROM golang:1.24 as builder
ARG CGO_ENABLED=0
WORKDIR .

COPY . .
RUN go mod download
RUN mkdir -p /go/bin/app
RUN go build -o /go/bin/app cmd/main.go

FROM scratch
COPY --from=builder /go/bin/app /go/bin/app
ENTRYPOINT ["/go/bin/app/main"]
EXPOSE 8080
